package com.ougong.shop;


import org.jetbrains.annotations.Nullable;

public interface MsgContract {

    String COMBO_SELECTED = "COMBO_SELECTED";
    String COMBO_SELECTED_RECOMMED = "COMBO_SELECTED_RECOMMED";
    String RESH_CHECKLIN_ROOM_CATEGORY = "RESH_CHECKLIN_ROOM_CATEGORY";
    String CHECKLIN_PRODUCT_JIA = "CHECKLIN_PRODUCT_JIA";
    String CHECKLIN_PRODUCT_JIAN = "CHECKLIN_PRODUCT_JIAN";
    String RESH_COMBO_NUM = "RESH_COMBO_NUM";
    String RESH_CHECKLIN_ROOM_NUM_PRICE = "RESH_CHECKLIN_ROOM_NUM_PRICE";
    String RESH_PROFILE_DATA = "RESH_PROFILE_DATA";
    String RESH_CHECKLIN_PRODUCT_SX = "RESH_CHECKLIN_PRODUCT_SX";
}
